import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createLeadHandler} from '../supabase/functions/submit-lead/handler.mjs';
const env={TURNSTILE_SECRET_KEY:'test',SUPABASE_SERVICE_ROLE_KEY:'test',SUPABASE_URL:'https://db.example'};
const base={name:'Test',email:'test@example.com',token:'test'};
async function run(extra){const calls=[];const h=createLeadHandler(env,async(url,opts)=>{calls.push({url,opts});return Response.json(url.includes('siteverify')?{success:true,hostname:'nolimitwebs.com',action:'quote_request'}:true);});const response=await h(new Request('https://example.test',{method:'POST',headers:{origin:'https://nolimitwebs.com','content-type':'application/json'},body:JSON.stringify({...base,...extra})}));return {response,calls,lead:calls[1]&&JSON.parse(calls[1].opts.body).lead_data};}
test('email-only inquiries succeed without SMS consent',async()=>{const r=await run({});assert.equal(r.response.status,200);assert.equal(r.lead.sms_consent.opted_in,false);assert.equal(r.lead.sms_consent.disclosure_version,null);});
test('consent requires a phone and exact supported disclosure version',async()=>{for(const extra of [{sms_consent:true},{sms_consent:true,phone:'3855550100'},{sms_consent:true,phone:'3855550100',sms_consent_version:'old'},{sms_consent:'true'}]){const r=await run(extra);assert.equal(r.response.status,400);assert.equal(r.calls.length,0);}});
test('consent proof uses server values and excludes promotional consent',async()=>{const r=await run({sms_consent:true,phone:'3855550100',sms_consent_version:'2026-09-15-v1',recorded_at:'1990-01-01',source_url:'https://evil.test',promotional_consent:true});assert.equal(r.response.status,200);const c=r.lead.sms_consent;assert.equal(c.opted_in,true);assert.equal(c.phone,'3855550100');assert.equal(c.source_url,'https://nolimitwebs.com/#contact');assert.equal(c.promotional_consent,false);assert.ok(Math.abs(Date.now()-Date.parse(c.recorded_at))<5000);const html=readFileSync(new URL('../site/index.html',import.meta.url),'utf8');assert.ok(html.includes(c.disclosure_text));});
test('checkbox is optional, unchecked and precedes submission; policies exist',()=>{const html=readFileSync(new URL('../site/index.html',import.meta.url),'utf8');const input=html.match(/<input[^>]+name="sms_consent"[^>]*>/)[0];assert.doesNotMatch(input,/\b(?:checked|required)\b/);assert.ok(html.indexOf('name="sms_consent"')<html.indexOf('type="submit"'));for(const p of ['privacy','terms'])assert.ok(readFileSync(new URL(`../site/${p}/index.html`,import.meta.url),'utf8').includes('Limitless Marketing Group LLC'));});
